sonar.projectKey=banco-java-puro
sonar.projectName=Sistema Bancario Java
sonar.projectVersion=1.0

# Credenciales por defecto
sonar.token=squ_0d453ea4fd06f29cc29341b0a21abf96a402f912
# sonar.password=Dark-blade28

# Rutas del proyecto
sonar.sources=src/main
sonar.tests=src/tests
sonar.java.binaries=bin
sonar.coverage.jacoco.xmlReportPaths=reportes/jacoco.xml
sonar.java.libraries=lib/*.jar