sonar.projectKey=banco-java-puro
sonar.projectName=Sistema Bancario Java
sonar.projectVersion=1.0

# Credenciales por defecto
sonar.login=squ_de97a8d81c580375b68a93598427a91a280d1d47
# sonar.password=Dark-blade28

# Rutas del proyecto
sonar.sources=src/main
sonar.tests=src/tests
sonar.java.binaries=bin
sonar.coverage.jacoco.xmlReportPaths=reportes/jacoco.xml
